Letter.create!(text: 'a', points: 2) if Letter.where(text: 'a').empty?
Letter.create!(text: 'b', points: 8) if Letter.where(text: 'b').empty?
Letter.create!(text: 'c', points: 8) if Letter.where(text: 'c').empty?
Letter.create!(text: 'd', points: 5) if Letter.where(text: 'd').empty?
Letter.create!(text: 'e', points: 2) if Letter.where(text: 'e').empty?
Letter.create!(text: 'f', points: 6) if Letter.where(text: 'f').empty?
Letter.create!(text: 'g', points: 6) if Letter.where(text: 'g').empty?
Letter.create!(text: 'h', points: 7) if Letter.where(text: 'h').empty?
Letter.create!(text: 'i', points: 2) if Letter.where(text: 'i').empty?
Letter.create!(text: 'j', points: 13) if Letter.where(text: 'j').empty?
Letter.create!(text: 'k', points: 8) if Letter.where(text: 'k').empty?
Letter.create!(text: 'l', points: 3) if Letter.where(text: 'l').empty?
Letter.create!(text: 'm', points: 5) if Letter.where(text: 'm').empty?
Letter.create!(text: 'n', points: 5) if Letter.where(text: 'n').empty?
Letter.create!(text: 'o', points: 2) if Letter.where(text: 'o').empty?
Letter.create!(text: 'p', points: 6) if Letter.where(text: 'p').empty?
Letter.create!(text: 'q', points: 15) if Letter.where(text: 'q').empty?
Letter.create!(text: 'r', points: 5) if Letter.where(text: 'r').empty?
Letter.create!(text: 's', points: 3) if Letter.where(text: 's').empty?
Letter.create!(text: 't', points: 3) if Letter.where(text: 't').empty?
Letter.create!(text: 'u', points: 4) if Letter.where(text: 'u').empty?
Letter.create!(text: 'v', points: 11) if Letter.where(text: 'v').empty?
Letter.create!(text: 'w', points: 10) if Letter.where(text: 'w').empty?
Letter.create!(text: 'x', points: 12) if Letter.where(text: 'x').empty?
Letter.create!(text: 'y', points: 4) if Letter.where(text: 'y').empty?
Letter.create!(text: 'z', points: 14) if Letter.where(text: 'z').empty?
Letter.create!(text: 'cl', points: 10) if Letter.where(text: 'cl').empty?
Letter.create!(text: 'er', points: 7) if Letter.where(text: 'er').empty?
Letter.create!(text: 'in', points: 7) if Letter.where(text: 'in').empty?
Letter.create!(text: 'qu', points: 9) if Letter.where(text: 'qu').empty?
Letter.create!(text: 'th', points: 9) if Letter.where(text: 'th').empty?
